# Generated by Django 2.1.4 on 2019-02-17 18:58

from django.db import migrations, models
import quiz.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to=quiz.helpers.RandomFileName('quiz/img'))),
            ],
        ),
    ]
