# Generated by Django 2.1.7 on 2019-02-20 01:12

from django.db import migrations, models
import quiz.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='img',
            field=models.ImageField(blank=True, upload_to=quiz.helpers.RandomFileName('map/img')),
        ),
    ]
