# Generated by Django 2.1.7 on 2019-03-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190220_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
