# Generated by Django 2.1.3 on 2018-11-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='path',
        ),
        migrations.AddField(
            model_name='question',
            name='a',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', models.TextField()), ('B', models.TextField()), ('C', models.TextField()), ('D', models.TextField())], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='b',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='c',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='d',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='descriptionImg',
            field=models.ImageField(default=1, upload_to='quiz/img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='questionImg',
            field=models.ImageField(default=1, upload_to='quiz/img/'),
            preserve_default=False,
        ),
    ]
