# Generated by Django 2.1.3 on 2018-11-26 22:30

from django.db import migrations, models
import quiz.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20181126_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='descriptionImg',
            field=models.ImageField(upload_to=quiz.helpers.RandomFileName('img/quiz')),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionImg',
            field=models.ImageField(upload_to=quiz.helpers.RandomFileName('img/quiz')),
        ),
    ]
