# Generated by Django 2.1.4 on 2019-02-09 19:39

from django.db import migrations, models
import django.db.models.deletion
import quiz.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20181129_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=quiz.helpers.RandomFileName('quiz/img'))),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='descriptionImg',
            field=models.ImageField(blank=True, upload_to=quiz.helpers.RandomFileName('quiz/img')),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionImg',
            field=models.ImageField(blank=True, upload_to=quiz.helpers.RandomFileName('quiz/img')),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
    ]
